addons:
  apt:
    packages:
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-fonts-extra
    - dvipng
    - texlive-latex-recommended
    - texlive-bibtex-extra
        
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build cv/lmarshall_cv.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build resume/lmarshall_resume.tex

deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - _build/lmarshall_cv.pdf
  - _build/lmarshall_resume.pdf
  skip_cleanup: true
  on:
    tags: true
